### ISSUE TITLE
License

### ISSUE THREAD

**Issue by napkindrawing** [cfsego/ngx_log_if#5]
There is currently no license associated with this repository.

For those of us who would like to use it without legal uncertainty can a license be added to the repo ( `LICENSE.md` ) and/or as a header comment to `ngx_http_aclog_bypass_module.c`?

OpenSource.org has templates for popular licenses:

* http://opensource.org/licenses/BSD-2-Clause
* http://opensource.org/licenses/LGPL-2.1
* http://opensource.org/licenses/GPL-2.0

Cheers,
Mike

**Comment by cfsego** [comment]
added
