### ISSUE TITLE
请问，可以支持upstream_response_time<3这种判断么？

### ISSUE THREAD

**Issue by blacktty** [cfsego/ngx_log_if#7]
这样相当于可以记录nginx后端的慢日志，很实用。

**Comment by cfsego** [comment]
这个不是我模块的功能，是nginx提供功能。他老人家什么时候支持<了就ok
https://github.com/alibaba/tengine/pull/159/files
是我的一个实现，其中条件判断的接口是和nginx完全兼容的，支持数值大小比较和与或非，只是没有把抽出来。
