### ISSUE TITLE
is it possible to disable access log if based on log content itself

### ISSUE THREAD

**Issue by ggeligible** [cfsego/ngx_log_if#8]
Hello Team,

We are trying to omit error logs in some cases and couldn't find any way to do that. I was thinking to write own module and found ngx_log_if, so I just wanted to check if its possible to disable access logs based on log content like

access_log_bypass_if ($log_content ~\* 'some string match');

then we will have to do something similar for error_logs or if its possible to quickly fork and make changes for error log as well. I am new to nginx modules so please bear with me is I am asking something very stupid.

Thanks a lot for you great work on the module. Looking forward to hear back.

**Comment by cfsego** [comment]
sorry for my latency, as long as the RTT to the sun.

Though error log is a core module, can be called by other cores and various modules, meanwhile there is a life cycle for this module, easily cause crash, what you want can perhaps be easy to achieve.

You can direct change ngx_log_error_core(), test your condition, and decide output to *p or not.
